#!/bin/bash
#PBS -N evaluate_task1
#PBS -l select=1:ncpus=4:ngpus=1:mem=128gb
#PBS -l walltime=01:00:00
#PBS -j oe

cd /srv/scratch/z5448549/DATA5925/

# IMPORTANT: Add the exact same 'module load' or 'source activate' 
# commands here that you used to start your 40-hour training job!
module load python/3.10.8
module load cuda/12.2.1
source test_env/bin/activate

python model1_val_task1.py --pth_file checkpoint/task1/model1_batchsize16_epochs50_embedsize128_layersnum4_headsnum8_cuda0_lr2e-05_seed0/2026_04_07_16_50_45.pth
